name: mc-as-a-service
version: 0.0.0
base: core20
summary: Minecraft server run as a service
description: Runs, configures, and helps manage a minecraft server. Designed with ubuntu core in mind
type: app
grade: devel
confinement: strict
architectures:
  - build-on: [amd64, arm64]
    run-on: all
apps:
  mc-run:
    command: bash $SNAP/bin/start.sh
    plugs:
      - network
      - network-bind
  mc-run-service:
    daemon: simple
    command: bash $SNAP/bin/start.sh
    stop-command: bash $SNAP/bin/stop.sh
    plugs:
      - network
      - network-bind
  mc-view:
    command: bash $SNAP/bin/view.sh
  mc-configure:
    command: bash $SNAP/bin/configure.sh
  mc-enable:
    command: bash $SNAP/bin/enable.sh
  mc-disable:
    command: bash $SNAP/bin/disable.sh
  mc-install:
    command: bash $SNAP/bin/install.sh

parts:
  dependencies:
    plugin: nil
    build-snaps:
      - links
    stage-packages:
      - openjdk-8-jre-headless
      - jq
      - nano
      - sed
      - whiptail
      - curl
  mc-server:
    source: https://github.com/matthew-salerno/mc-as-a-service.git
    source-type: git
    plugin: dump
    organize:
        '*.json': etc/
        '*.sh': bin/
 
