name: minecraft-as-a-service
version: 0.0.0
summary: Minecraft server run as a service
description: Runs, configures, and helps manage a minecraft server. Designed with ubuntu core in mind
type: app
grade: devel
confinement: strict
architectures:
  - build-on: [amd64, arm64]
    run-on: all
apps:
  mc-run-gui:
    command: bash $SNAP/bin/start.sh
    plugs:
      - network
      - network-bind
  mc-run-no-gui:
    daemon: simple
    command: bash $SNAP/bin/start.sh
    stop-command: bash $SNAP/bin/stop.sh
    plugs:
      - network
      - network-bind
  mc-configure:
    command: bash $SNAP/bin/configure.sh
  mc-enable:
    command: bash $SNAP/bin/enable.sh
  mc-enable:
    command: bash $SNAP/bin/disable.sh

parts:
  mc-server:
    source: https://github.com/matthew-salerno/mc-as-a-service.git
    source-type: git
    plugin: nil

    stage-packages:
      - openjdk-8-jre-headless
      - jq
      - nano
    plugin: dump
    organize:
        '*.json': config/
        '*.sh': bin/
 
