name: mc-as-a-service
version: 0.0.0
base: core20
summary: Minecraft server run as a service
description: Runs, configures, and helps manage a minecraft server. Designed with ubuntu core in mind
type: app
grade: devel
confinement: strict
architectures:
  - build-on: [amd64, arm64]
    run-on: all

slots:
  dbus-slot:
    interface: dbus
    bus: system
    name: com.salernosection.mc_as_a_service

plugs:
  dbus-plug:
    bus: system
    interface: dbus
    name: com.salernosection.mc_as_a_service
        
apps:
  mc-manager:
    command: bin/python3 $SNAP/mc_manager
    plugs:
      - dbus-plug
        
  mc-service:
    daemon: simple
    command: bin/python3 $SNAP/mc_service
    stop-command: bin/python3 $SNAP/mc_manager stop-service
    plugs:
      - network
      - network-bind
    slots: [ dbus-slot ]

parts:
  dependencies:
    source: https://github.com/matthew-salerno/mc-as-a-service.git
    source-type: git
    plugin: python
    stage-packages:
      - openjdk-8-jre-headless
    requirements:
      - requirements.txt

  mc-server:
    source: https://github.com/matthew-salerno/mc-as-a-service.git
    source-type: git
    plugin: dump

    
