name: mc-as-a-service
version: 0.0.0
base: core20
summary: Minecraft server run as a service
description: Runs, configures, and helps manage a minecraft server. Designed with ubuntu core in mind
type: app
grade: devel
confinement: strict
architectures:
  - build-on: [amd64, arm64]
    run-on: all
apps:
  mc-manager:
    command: python3 mc_manager
    plugs:
      - dbus
  mc-service:
    daemon: simple
    command: mc_service
    stop-command: python3 mc_manager stop-service
    plugs:
      - network
      - network-bind
      - dbus

parts:
  dependencies:
    source: https://github.com/matthew-salerno/mc-as-a-service.git
    source-type: git
    plugin: python
    stage-packages:
      - openjdk-8-jre-headless
    requirements:
      - requirements.txt

  mc-server:
    source: https://github.com/matthew-salerno/mc-as-a-service.git
    source-type: git
    plugin: dump
 
