name: maas
title: Minecraft As A Service
base: core20
version: 0.0.0
summary: Minecraft server run as a service
description: Runs, configures, and helps manage a minecraft server. Designed with ubuntu core in mind
type: app
grade: devel
confinement: strict
license: unlicense
architectures:
  - build on: [amd64, arm64]
    run on: all
apps:
  mc-run-gui:
    command: bash $SNAP/bin/start.sh
    plugs:
      - network
      - network-bind
  mc-run-no-gui:
    deamon: simple
    command: bash $SNAP/bin/start.sh
    stop-command: $SNAP/bin/stop.sh
    plugs:
      - network
      - network-bind
  mc-configure:
    command: command: bash $SNAP/bin/configure.sh
  mc-enable:
    command: command: bash $SNAP/bin/enable.sh
  mc-enable:
    command: command: bash $SNAP/bin/disable.sh

parts:
  mc-server-installer:
    source: https://github.com/matthew-salerno/mc-server-installer
    source-type: git
    plugin: nil
    
    build-packages:
      - openjdk-8-jre-headless
      - curl
      - sed
      - jq
      - nano

      
    stage-packages:
      - openjdk-8-jre-headless
      - curl
      - sed
      - jq
      - nano


  publish:
    source: https://github.com/matthew-salerno/mc-server-installer
    source-type: git
    plugin: dump
 
