name: mc-as-a-service
version: 1.0.0a1.dev1
base: core20
summary: Minecraft server run as a service
description: Runs, configures, and helps manage a minecraft server. Designed with ubuntu core in mind
type: app
grade: devel
confinement: strict
architectures:
  - build-on: [amd64]
    run-on: amd64

slots:
  dbus-slot:
    interface: dbus
    bus: system
    name: com.salernosection.mc_as_a_service

plugs:
  dbus-plug:
    interface: dbus
    bus: system
    name: com.salernosection.mc_as_a_service
        
apps:
  mc-manager:
    command: bin/python3 $SNAP/mc_manager
    plugs:
      - dbus-plug
    environment:
      GI_TYPELIB_PATH: $SNAP/usr/lib/girepository-1.0:$SNAP/usr/lib/x86_64-linux-gnu/girepository-1.0
        
  mc-service:
    daemon: simple
    command: bin/python3 $SNAP/mc_service
    stop-command: bin/python3 $SNAP/mc_manager stop-service
    plugs:
      - network
      - network-bind
    slots: [ dbus-slot ]
    environment:
      GI_TYPELIB_PATH: $SNAP/usr/lib/girepository-1.0:$SNAP/usr/lib/x86_64-linux-gnu/girepository-1.0

parts:
  dependencies:
    plugin: python
    override-build: |
      snapcraftctl build
      pip3 install wheel; pip3 install dirsync; pip3 install --no-deps PyGObject
    source: .
    build-packages:
      - ca-certificates
      - ca-certificates-java
      - openjdk-8-jre-headless
      - libgirepository1.0-dev
      - gcc
      - pkg-config
      - gir1.2-glib-2.0
      - gir1.2-freedesktop
    stage-packages:
      - libgirepository1.0-dev
      - openjdk-8-jre-headless
      - gir1.2-glib-2.0
      - gir1.2-freedesktop
    python-packages:
      - urllib3
      - pydbus
  mc-server:
    source: https://github.com/matthew-salerno/mc-as-a-service.git
    source-type: git
    plugin: dump

    