name: mc-as-a-service
version: 0.0.0
base: core20
summary: Minecraft server run as a service
description: Runs, configures, and helps manage a minecraft server. Designed with ubuntu core in mind
type: app
grade: devel
confinement: strict
architectures:
  - build-on: [amd64, arm64]
    run-on: all

slots:
  dbus-slot:
    interface: dbus
    bus: system
    name: com.salernosection.mc_as_a_service

plugs:
  dbus-plug:
    bus: system
    interface: dbus
    name: com.salernosection.mc_as_a_service
        
apps:
  mc-manager:
    command: bin/python3 $SNAP/mc_manager
    plugs:
      - dbus-plug
        
  mc-service:
    daemon: simple
    command: bin/python3 $SNAP/mc_service
    stop-command: bin/python3 $SNAP/mc_manager stop-service
    plugs:
      - network
      - network-bind
    slots: [ dbus-slot ]

parts:
  dependencies:
    plugin: python
    override-build: |
      snapcraftctl build
      pip3 install wheel; pip3 install pydbus dirsync; pip3 install pycairo; pip3 install PyGObject
    source: .
    build-packages:
      - python3-pip
      - libgirepository1.0-dev
      - gcc
      - libcairo2-dev
      - pkg-config
      - gir1.2-glib-2.0
      - gir1.2-freedesktop
      - libcairo-gobject2
      - python3-gi
      - python3-gi-cairo
    stage-packages:
      - libgirepository1.0-dev
      - libcairo-gobject2
      - libcairo2-dev
      - libfontconfig1
      - libfreetype6
      - libpixman-1-0
      - libpng16-16
      - libx11-6
      - libxau6
      - libxcb-render0
      - libxcb-shm0
      - libxcb1
      - libxdmcp6
      - libxext6
      - libxrender1
      - openjdk-8-jre-headless
      - gir1.2-glib-2.0
      - gir1.2-freedesktop
      - pkg-config 
      - gcc
  mc-server:
    source: https://github.com/matthew-salerno/mc-as-a-service.git
    source-type: git
    plugin: dump

    
